CHANGELOG.md, README.md
lots of work is still required; very early alpha
=> updating and fixing the readme

complete_build.sh, scripts/00_createScriptReferences.sh, scripts/all_balances.sh, validators/always_false.ak
Need a script that will perma hold the script reference for a given random string.
=> now the script refernce lives in an always false contract

seedelf-cli/src/assets.rs, seedelf-cli/src/commands/fund.rs, seedelf-cli/src/commands/sweep.rs, seedelf-cli/src/commands/transfer.rs, seedelf-cli/src/lib.rs, seedelf-cli/src/main.rs, seedelf-cli/tests/assets_test.rs
Adding in the asset class. This should allow the wallet to interact with assets nicely. All amounts that were ADA are now called Lovelace to reflect the purpose.
=> Add asset type

seedelf-cli/src/assets.rs, seedelf-cli/src/koios.rs, seedelf-cli/src/lib.rs, seedelf-cli/src/transaction.rs, seedelf-cli/src/utxos.rs, seedelf-cli/tests/utxos_test.rs
Simple largest first algo with change detection
=> Add utxo collection and selection

seedelf-cli/src/main.rs
The default wallet loading function should not run during --help or --version
=> loading wallet should not happen on version and help

seedelf-cli/README.md, seedelf-cli/static/index.css, seedelf-cli/static/index.html, seedelf-cli/static/index.js
I cleaned up some text and added a dropdown for all the installed wallets. The timeout for wallet selection has been increased.
=> web interface should work for many wallets now

seedelf-cli/static/index.js
Now wallets in the dropdown are sorted alphabetically.
=> should fix it

seedelf-cli/src/data_structures.rs, seedelf-cli/src/display.rs, seedelf-cli/src/transaction.rs, seedelf-cli/tests/address_test.rs, seedelf-cli/tests/display_test.rs
If it can't be displayed correctly then skip it.
=> Should be able to extract the label, clean it up, and display it

seedelf-cli/Cargo.toml, seedelf-cli/src/commands/balance.rs, seedelf-cli/src/commands/create.rs, seedelf-cli/src/commands/fund.rs, seedelf-cli/src/commands/remove.rs, seedelf-cli/src/commands/sweep.rs, seedelf-cli/src/commands/transfer.rs, seedelf-cli/src/commands/welcome.rs, seedelf-cli/src/display.rs, seedelf-cli/src/setup.rs, seedelf-cli/src/web_server.rs
closes #46 
Also fixes an issue with change that contains only lovelace and no tokens
=> 46 add colors to display text

seedelf-cli/src/commands/transfer.rs, seedelf-cli/tests/assets_test.rs
Transfer was not selecting tokens correctly. Everything should be working as expected now.
should close #48
=> change utxo functionality test

.github/workflows/release.yml
Should close #51 will need to test
=> should build then upload and build the release notes

seedelf-cli/README.md, seedelf-init.sh
=> 50 build bash one liner for quick install

seedelf-cli/src/setup.rs
should fix #59 
windows and mac should path correctly now
=> using dirs home should allow cross platform pathing

seedelf-cli/src/commands/sweep.rs, seedelf-cli/src/constants.rs, seedelf-cli/src/koios.rs, seedelf-cli/tests/assets_test.rs, seedelf-cli/tests/koios_test.rs
should close #61 
The tricky thing is that old ada handles are just the name, and the new ones are cip 68. So we have to check for both.
=> 61 sweep to ada handle functionality

seedelf-cli/Cargo.toml, seedelf-cli/README.md, seedelf-cli/src/commands/mod.rs, seedelf-cli/src/commands/update.rs, seedelf-cli/src/main.rs
This one can only be tested with a new tag release. So push a tag and test it. If fixes are required then do a chore or open a new issue. This should fixed #63
=> 63 cli auto update functionality

seedelf-cli/README.md, seedelf-cli/src/commands/mod.rs, seedelf-cli/src/commands/util/expose_key.rs, seedelf-cli/src/commands/util/mod.rs, seedelf-cli/src/main.rs
Make new issues for utility functions we need to add to the util subcommand. This should fix #65
=> 65 build a subcommand of utility

seedelf-cli/src/commands/util/find_seedelf.rs, seedelf-cli/src/commands/util/mod.rs, seedelf-cli/src/display.rs, seedelf-cli/src/main.rs, seedelf-cli/src/utxos.rs
should fix #68 
The search label must be in hex for now. To view all seedelfs in the contract, pass the empty string as the label.
=> a very fuzzy seedelf search in hex

seedelf-cli/src/commands/util/mod.rs, seedelf-cli/src/commands/util/statistics.rs, seedelf-cli/src/utxos.rs
=> 70 count total lovelace and utxos in contract

seedelf-cli/Cargo.toml, seedelf-cli/src/web_server.rs
=> static files should be forced to be included inside binaries on all platforms

seedelf-cli/src/commands/transfer.rs, seedelf-cli/src/commands/util/extract.rs, seedelf-cli/src/commands/util/mod.rs, seedelf-cli/src/koios.rs
should close #77 . Allows a wallet to spend a utxo that does not contain a datum.
=> added a datumless extraction util command

seedelf-cli/src/commands/util/mint.rs, seedelf-cli/src/commands/util/mod.rs, seedelf-cli/src/koios.rs, seedelf-cli/src/utxos.rs
=> Added seedelf mint from inside the wallet

seedelf-cli/Cargo.toml, seedelf-cli/src/address.rs, seedelf-cli/src/commands/dapp/balance.rs, seedelf-cli/src/commands/dapp/mod.rs, seedelf-cli/src/commands/mod.rs, seedelf-cli/src/convert.rs, seedelf-cli/src/lib.rs, seedelf-cli/src/main.rs, seedelf-cli/src/utxos.rs, seedelf-cli/tests/convert_test.rs
=> 81 create dapp wallet from scalar

seedelf-cli/Cargo.toml, seedelf-cli/src/address.rs, seedelf-cli/src/commands/dapp/balance.rs, seedelf-cli/src/commands/dapp/mod.rs, seedelf-cli/src/commands/dapp/sweep.rs, seedelf-cli/src/commands/mod.rs, seedelf-cli/src/convert.rs, seedelf-cli/src/lib.rs, seedelf-cli/src/main.rs, seedelf-cli/src/utxos.rs, seedelf-cli/tests/convert_test.rs
Solid base for dapp interactions.
=> Initial Dapp integration

seedelf-cli/Cargo.toml, seedelf-cli/src/hashing.rs, seedelf-cli/tests/hashing_test.rs
=> add sha3_256 to hashing

seedelf-cli/src/hashing.rs, seedelf-cli/tests/hashing_test.rs
=> adding blake2b_256

seedelf-cli/Cargo.toml, seedelf-cli/tests/hashing_test.rs
=> bumping cargo toml versions

seedelf-cli/src/koios.rs, seedelf-cli/tests/koios_test.rs
=> Added ability to query the last N transactions of an asset

seedelf-cli/src/address.rs, seedelf-cli/src/commands/dapp/balance.rs
=> returns the stake key used in the constants file for logic

seedelf-cli/src/commands/dapp/newm/guide.rs, seedelf-cli/src/commands/dapp/newm/mod.rs
=> 102 add newm guide command

README.md, seedelf-cli/README.md, seedelf-cli/src/commands/fund.rs, seedelf-cli/src/commands/sweep.rs, seedelf-cli/src/commands/transfer.rs, seedelf-cli/src/commands/welcome.rs, seedelf-contracts/README.md
=> 110 update main readme

LICENSE, RELEASE.md, SECURITY.md
=> 112 update security and release readme

seedelf-cli/src/commands/create.rs, seedelf-cli/src/commands/external/sweep.rs, seedelf-cli/src/commands/remove.rs, seedelf-cli/src/commands/sweep.rs, seedelf-cli/src/commands/transfer.rs, seedelf-cli/src/commands/util/extract.rs, seedelf-cli/src/commands/util/migrate.rs, seedelf-cli/src/commands/util/mint.rs, seedelf-cli/src/display.rs, seedelf-cli/src/utxos.rs
=> 126 add better error messaging for koios queries

seedelf-cli/src/commands/util/history.rs, seedelf-cli/src/commands/util/mod.rs, seedelf-cli/src/koios.rs
=> 128 add view transaction history to util

README.md
=> 138 add a section about ip tracking via koiosrest and givememy

seedelf-cli/src/commands/fund.rs, seedelf-cli/src/commands/sweep.rs, seedelf-cli/src/commands/transfer.rs, seedelf-cli/src/commands/util/find.rs, seedelf-cli/src/commands/welcome.rs
=> assets now use the requires field

seedelf-cli/src/commands/balance.rs, seedelf-cli/src/commands/fund.rs, seedelf-cli/src/commands/sweep.rs, seedelf-cli/src/commands/transfer.rs, seedelf-cli/src/commands/util/extract.rs, seedelf-cli/src/commands/util/mint.rs, seedelf-cli/src/utxos.rs, seedelf-cli/tests/utxos_test.rs
=> 148 add utxo selection to transfer and sweep

.github/workflows/continuous-integration.yml, seedelf-contracts/aiken.toml
=> aiken bumped to 1.17

README.md, seedelf-contracts/README.md, seedelf-platform/README.md
=> all links should work now

seedelf-platform/seedelf-gui/src/components/Checkbox.tsx, seedelf-platform/seedelf-gui/src/components/TextField.tsx, seedelf-platform/seedelf-gui/src/components/TopNavBar.tsx, seedelf-platform/seedelf-gui/src/pages/NewWallet.tsx, seedelf-platform/seedelf-gui/src/pages/Wallet/Dashboard.tsx, seedelf-platform/seedelf-gui/src/pages/Wallet/Extract.tsx, seedelf-platform/seedelf-gui/src/pages/Wallet/Fund.tsx, seedelf-platform/seedelf-gui/src/pages/Wallet/History.tsx, seedelf-platform/seedelf-gui/src/pages/Wallet/Manage.tsx, seedelf-platform/seedelf-gui/src/pages/Wallet/Receive.tsx, seedelf-platform/seedelf-gui/src/pages/Wallet/Send.tsx
=> 192 add hover help question mark icons on each page

seedelf-platform/seedelf-cli/static/index.css, seedelf-platform/seedelf-gui/index.html, seedelf-platform/seedelf-gui/src/components/Checkbox.tsx, seedelf-platform/seedelf-gui/src/components/ConfirmationModal.tsx, seedelf-platform/seedelf-gui/src/components/LoadingOverlay.tsx, seedelf-platform/seedelf-gui/src/components/ShowNotification.tsx, seedelf-platform/seedelf-gui/src/components/Toggle.tsx, seedelf-platform/seedelf-gui/src/components/TopNavBar.tsx, seedelf-platform/seedelf-gui/src/pages/NewWallet.tsx, seedelf-platform/seedelf-gui/src/pages/Wallet/Dashboard.tsx, seedelf-platform/seedelf-gui/src/pages/Wallet/Extract.tsx, seedelf-platform/seedelf-gui/src/pages/Wallet/Fund.tsx, seedelf-platform/seedelf-gui/src/pages/Wallet/History.tsx, seedelf-platform/seedelf-gui/src/pages/Wallet/Manage.tsx, seedelf-platform/seedelf-gui/src/pages/Wallet/Receive.tsx, seedelf-platform/seedelf-gui/src/pages/Wallet/Send.tsx, seedelf-platform/seedelf-gui/src/pages/Wallet/Sidebar.tsx, seedelf-platform/seedelf-gui/src/pages/Wallet/WalletLayout.tsx, seedelf-platform/seedelf-gui/src/pages/Wallet/colors.ts, seedelf-platform/seedelf-gui/src/styles/globals.css
The tailwind class neutral-300 is now the default white, its near e5e5e5. Placeholder text is os specific so leave it for the system default.
=> 219 add white to the color class
